Develop
polinapechenkova/development pull request #5
Opened 2023-12-20 19:58 UTC by polinapechenkova

Здравствуйте! 
Никак не удается реализовать отправку файлов через Fork.
Добавила здесь в ручную, надеюсь, все подгрузилось корректно.

2023-12-20 20:07 UTC, Levitinn requested changes

2023-12-20 20:07 UTC, Levitinn commented on 4-navigator
> +console.log(distance);
```
const distance = Math.sqrt(((addressLat - positionLat)**2) + ((addressLong - positionLong)**2))
console.log( `Дистанция от объекта равна: ${distance}.`);
```
изначально, ты пытаешься засунуть в переменную значение дистанции.
в переменную мы кладем значения, которые рассчитываем где то использовать, но  на 9 строке, ты добавила текст в эту переменную, что делаешь невозможным ее переиспользование, так как в нем уже текст. 
не нужно засорять переменные не нужной информацией. оставь только дистанцию

2023-12-20 20:07 UTC, Levitinn commented on 5-languages
в этом файле нет отступов. про них нельзя забывать

2023-12-21 15:41 UTC, polinapechenkova commented on 5-languages
Добавлены отступы: 

const lang = prompt('What language do you speak?');

switch(true) {    
   case lang === 'en':
      console.log('Good day!');    
      break;
   case lang === 'de':
      console.log('Gutten tag!');    
      break;
   case lang === 'ru':
      console.log('Добрый день!');    
      break;
   default: 
}

console.log('We don’t speak this language yet :(');

2023-12-21 20:03 UTC, merged